---
apiVersion: v1
kind: Service
metadata:
  name: kubedns-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  selector:
    app: kube-dns
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53    
