apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-pod
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
    - mountPath: "/data"
      name: csi-data-volume
    command: [ "sleep", "10000000" ]

  volumes:
    - name: csi-data-volume
      persistentVolumeClaim:
        claimName: storage-pvc