apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-monitoring
  endpoints:
  - port: exporter