apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-monitoring
  name: web
  namespace: default
spec:
  ports:
  - name: exporter
    port: 9113
    targetPort: 9113
  - name: web
    port: 8000
    targetPort: 8000
  selector:
    app: testweb
  type: ClusterIP