apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-monitoring
  labels:
    app: svc-nginx-monitoring
spec:
  selector:
    app: nginx-monitoring
  type:  ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: metrics
      port: 9113
      protocol: TCP
      targetPort: 9113