apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: acme-cert-tls
  issuerRef:
    name: test-selfsigned